-- Replaces broken 0004_rag_rls.sql which referenced non-existent tables
-- from a prior incomplete RAG attempt. All RLS for new tables is set in
-- the migration that creates each table.
-- This file is kept as a no-op placeholder to preserve migration numbering.